### PR TITLE
[DEVOPS-142]  Implement a global --debug flag for all deployment scripts

### PR DESCRIPTION
**Pull request by deepfire**
This is to:

1. allow `--debug` passed to most `nixops` commands
2. facilitate easier future options definitions

### CODE REVIEW

**Comment by domenkozar** [comment]
Let's just always pass `--debug`. Not having tracebacks is a bad idea in the first place, because of issues like https://github.com/NixOS/nixops/issues/677

*nitpick: please always separate styling changes from features/bugs*

**Comment by deepfire** [comment]
@domenkozar, I will undo the reindentation.

**Comment by deepfire** [comment]
Ok, instead of undoing them, I separated them into a separate commit (the styling changes were fairly minor, though), @domenkozar.

**Comment by deepfire** [comment]
@domenkozar, I have played with adding `--debug` to `nixops deploy` -- and the unconditional XML dump is absolutely _terrifying_.

I think we should leave `--debug` as an option.

What do you think?

**Comment by domenkozar** [comment]
Makes sense, let's leave `--debug` as an option then.

**Pull request merged**
