### PR TITLE
Allow intero to be used to develop the Haskell scripts

### PR DESCRIPTION
**Pull request by deepfire**
This allows `intero` to be used for the `iohk-nixops` script development.

Note that this requires a matching version of the `intero` emacs package.

(Just as a side note -- that's how I install emacs with packages: https://github.com/deepfire/bin/blob/master/nix/emacs.nix)

### CODE REVIEW

**Comment by deepfire** [comment]
@jmitchell, renamed to `nixpkgs-shell.json`, I think that should do that..

**Comment by domenkozar** [comment]
It's not entirely clear to me why we need `stack.yaml` and `shell.nix`?

I'm not against intero support, but I think we should rather first make our nixops wrapper a proper haskell package and then add editor support.

**Comment by domenkozar** [comment]
Also this adds yet another source of `nixpkgs` pinning. It seems in general it's too early to merge, as we haven't figured out the foundamentals here.

**Comment by deepfire** [comment]
@domenkozar, `stack.yaml` is required for intero, unfortunately, `shell.nix` for establishing the dependencies for the haskell scripts.

**Comment by deepfire** [comment]
@domenkozar, it seems the merge should be undone -- I've let myself to be convinced by Jake that we can incrementally improve upon this PR : -)

**Pull request merged**
