### PR TITLE
intero | fix:  move stack.yaml to the cabal file to heal intero startup

### PR DESCRIPTION
**Pull request by deepfire**
This fixes `intero` loadability wrt. `iohk-ops`.

### CODE REVIEW

**Comment by domenkozar** [comment]
@cleverca22 another instance of stack2nix failures.

**Comment by deepfire** [comment]
@domenkozar, as we have previously discussed, this isn't supposed to be handled by `stack directly -- or by `stack2nix` -- this is purely an enabler for `intero`.

**Comment by domenkozar** [comment]
@deepfire I'm commenting about the unrelated CI issue

**Comment by deepfire** [comment]
Oh, I see, indeed : -)

**Pull request merged**
